### ISSUE TITLE
[REQUEST] the hook should result in an error if the defined/required runtime does not match what is defined in the requirements/lock file

### ISSUE THREAD

**Issue by ITProKyle** [ITProKyle/runway-hook-awslambda#55]
For example, if I tell the hook the runtime should be `python3.7` and the `pyproject.toml` file in the project contains the following, it should result in an error.

```toml
[tool.poetry.dependencies]
python = "^3.8"
```

However, if I tell the hook the runtime is `python3.8` or `python3.9`, it should pass.
