### ISSUE TITLE
[REQUEST] support using requirement & lock files located outside of the source code directory

### ISSUE THREAD

**Issue by ITProKyle** [ITProKyle/runway-hook-awslambda#63]
Example file structure:

```
.
├── pipenv_test.cfn
│   ├── cfngin.yml
│   ├── poetry.lock
│   ├── pyproject.toml
│   └── src
│       └── index.py
└── runway.yml
```

In this use case, the `pipenv_test.cfn/src/` directory contains the source code and the `pipenv_test.cfn/` directory contains the lock file.

Currently, the CFNgin config would need to look like this to include dependencies in the deployment package:

```yaml
pre_deploy:
  - path: awslambda.PythonFunction
    data_key: awslambda.test-function
    args:
      extend_gitignore:
        - cfngin.yml
      source_code: ./
      ...
```

But, the desired config would be:

```yaml
pre_deploy:
  - path: awslambda.PythonFunction
    data_key: awslambda.test-function
    args:
      extend_gitignore:
        - cfngin.yml
      source_code: ./src
      ...
```
